/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wsCalculadora;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Calculadora c = new Calculadora();

        System.out.println(new App().getGreeting());
        System.out.println("CALCULADORA");
        System.out.println("---------------------------------------");
        System.out.println("Exp(0) = " + c.exp(1));
        System.out.println("Exp(1) = " + c.exp(1));
        System.out.println("Exp(5) = " + c.exp(5));
        System.out.println("Exp(10) = " + c.exp(10));
        System.out.println("Exp(33) = " + c.exp(33));

    }
}