/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package wsCalculadora;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Calculadora c = new Calculadora();

        System.out.println(new App().getGreeting());
        System.out.println("CALCULADORA");
        System.out.println("---------------------------------------");
        System.out.println("log(1) = " + (int) c.log(1));
        System.out.println("log(10) = " + (int) c.log(10));
        System.out.println("log(100) = " + (int) c.log(100));

    }
}